channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pandas=0.25
  - xlrd
  - boto3
  - apscheduler
  - numpy
  - jupyterlab
  - pip=19.3.1
  - pip:
      - lektor==3.1.3
      - requests==2.21.0
      - tweepy==3.8.0

