name: PyConDE-www
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0
  - apscheduler=3.6.1
  - attrs=19.3.0
  - backcall=0.1.0
  - bleach=3.1.0
  - boto3=1.9.250
  - botocore=1.12.253
  - ca-certificates=2019.9.11
  - certifi=2019.6.16
  - decorator=4.4.0
  - defusedxml=0.6.0
  - docutils=0.15.2
  - entrypoints=0.3
  - importlib_metadata=0.23
  - ipykernel=5.1.3
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - jedi=0.15.1
  - jmespath=0.9.4
  - json5=0.8.5
  - jsonschema=3.1.1
  - jupyter_client=5.3.3
  - jupyter_core=4.5.0
  - jupyterlab=1.1.4
  - jupyterlab_server=1.0.6
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=9.0.0
  - libffi=3.2.1
  - libgfortran=4.0.0
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libsodium=1.0.17
  - llvm-openmp=9.0.0
  - mistune=0.8.4
  - more-itertools=7.2.0
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=6.0.1
  - numpy=1.17.2
  - openssl=1.1.1c
  - pandas=0.25.2
  - pandoc=2.7.3
  - pandocfilters=1.4.2
  - parso=0.5.1
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.3.1
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - ptyprocess=0.6.0
  - pygments=2.4.2
  - pyrsistent=0.15.4
  - pysocks=1.7.1
  - python=3.6.7
  - python-dateutil=2.8.0
  - pyzmq=18.1.0
  - readline=7.0
  - s3transfer=0.2.1
  - send2trash=1.5.0
  - setuptools=41.4.0
  - sqlite=3.28.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.9
  - tornado=6.0.3
  - traitlets=4.3.3
  - tzlocal=2.0.0
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - xlrd=1.2.0
  - xz=5.2.4
  - zeromq=4.3.2
  - zipp=0.6.0
  - zlib=1.2.11
  - pip:
    - argh==0.26.2
    - asn1crypto==0.24.0
    - babel==2.6.0
    - cachetools==3.1.1
    - cffi==1.11.5
    - chardet==3.0.4
    - click==7.0
    - cryptography==2.5
    - et-xmlfile==1.0.1
    - exifread==2.1.2
    - flask==1.0.2
    - google-api-python-client==1.7.11
    - google-auth==1.6.3
    - google-auth-httplib2==0.0.3
    - google-auth-oauthlib==0.4.0
    - httplib2==0.13.1
    - idna==2.8
    - inifile==0.4
    - itsdangerous==1.1.0
    - jdcal==1.4.1
    - jinja2==2.10.1
    - lektor==3.1.3
    - markupsafe==1.1.0
    - oauth2client==4.1.3
    - oauthlib==3.1.0
    - openpyxl==2.6.2
    - pathtools==0.1.2
    - pyasn1==0.4.6
    - pyasn1-modules==0.2.6
    - pycparser==2.19
    - pyopenssl==19.0.0
    - pytz==2018.9
    - pyyaml==4.2b1
    - requests==2.21.0
    - requests-oauthlib==1.2.0
    - rsa==4.0
    - six==1.12.0
    - tweepy==3.8.0
    - uritemplate==3.0.0
    - urllib3==1.24.3
    - watchdog==0.9.0
    - werkzeug==0.14.1
